ci: add descriptive names and a summary job
This makes it easier to distinguish and manage them in Github

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -55,3 +55,16 @@ jobs:
 
           nim c -r test.nim
         shell: bash
+
+  success:
+    name: All action tests passed
+    needs: [check]
+    if: always()
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Raise failure
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: |
+          echo "::error::There are failing required jobs"
+          exit 1
